include: lib/package.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
linter:
  rules:
    # custom rules
    avoid_print: false # overwritten
    public_member_api_docs: false # overwritten
    # new rules
