name: Install tools
description: Installs required operating system tools
inputs:
  withDartTestTools:
    required: false
    default: "false"
    description: Also install dart_test_tools as global dart tool.
runs:
  steps:
    - id: setup-dart-install
      name: Setup dart install path
      run: |
        $ErrorActionPreference = "Stop"
        $dataHomePath = Join-Path $env:RUNNER_TOOL_CACHE "dart"
        Add-Content -Path $Env:GITHUB_ENV -Value "DART_DATA_HOME=$dataHomePath"
        Add-Content -Path $Env:GITHUB_PATH -Value (Join-Path $dataHomePath "install" "bin")
        Add-Content -Path $Env:GITHUB_OUTPUT -Value "dart-version=$(Get-Content (Join-Path (Split-Path (Split-Path (Get-Command dart).Source)) "version"))"
      shell: pwsh
    - name: Cache dart install tools
      uses: actions/cache@v5
      with:
        key: dart_tools-${{ runner.os }}-${{ steps.setup-dart-install.outputs.dart-version }}
        path: ${{ runner.tool_cache }}/dart/install
    - name: Install scoop
      if: runner.os == 'Windows'
      run: |
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
      shell: pwsh
    - name: Install yq (Windows)
      if: runner.os == 'Windows'
      run: scoop install yq
      shell: pwsh
    - name: Install coreutils (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install coreutils
        echo "$(brew --prefix)/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH
      shell: bash
    - name: Install dart_test_tools
      if: inputs.withDartTestTools == 'true'
      run: dart install dart_test_tools ^7.1.1
      shell: bash
  using: composite
