name: Install hurl
description: Install hurl
runs:
  using: composite
  steps:
    - name: Install hurl from GitHub releases
      if: runner.os	== 'Linux'
      run: |
        set -eo pipefail

        echo ::group::Detect latest version
        hurl_file='${{ runner.temp }}/hurl.json'
        curl -sSLfo "$hurl_file" 'https://api.github.com/repos/Orange-OpenSource/hurl/releases/latest'
        echo "Installing Hurl Version $(jq -r '.name' "$hurl_file")"
        download_url=$(jq -r '.assets[] | select (.name | endswith(".deb")) | .browser_download_url' "$hurl_file")
        echo ::endgroup::

        echo ::group::Download hurl
        hurl_deb='${{ runner.temp }}/hurl.deb'
        curl -Lfo "$hurl_deb" "$download_url"
        echo ::endgroup::

        echo ::group::Install hurl
        sudo apt install "$hurl_deb"
        echo ::endgroup::
      shell: bash
    - name: Install hurl from homebrew
      if: runner.os	== 'macOS'
      run: brew install hurl
      shell: bash
    - name: Install hurl from winget
      if: runner.os	== 'Windows'
      run: winget install hurl
      shell: powershell
