on:
  workflow_call:
    inputs:
      flutterSdkChannel:
        type: string
        required: false
        default: stable
        description: The Flutter-SDK channel. Passed as "channel" to "subosito/flutter-action".
      workingDirectory:
        type: string
        required: false
        default: .
        description: The root directory of the dart package to build and test.
    secrets:
      githubToken:
        required: true
        description: The personal access token to create new releases with. Is required, as the default github workflow token does not trigger workflows when creating releases.
jobs:
  check-update-required:
    name: Check if updates are required
    outputs:
      needs_update: ${{ steps.check_auto_update.outputs.needs_update }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter-SDK (${{ inputs.flutterSdkChannel }})
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.flutterSdkChannel }}
          cache: true
      - name: Download flutter binary artifacts
        run: flutter precache --universal
      - name: Install dart_test_tools
        run: dart pub global activate dart_test_tools ^6.1.3-pre.2
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Restore dart packages
        run: flutter pub get
        working-directory: ${{ inputs.workingDirectory }}
      - id: check_auto_update
        name: Check if updates are needed
        run: flutter pub global run dart_test_tools:auto_update '${{ inputs.workingDirectory }}'
  auto-update:
    name: Automatic dependency updates
    needs:
      - check-update-required
    if: needs.check-update-required.outputs.needs_update == 'true'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter-SDK (${{ inputs.flutterSdkChannel }})
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.flutterSdkChannel }}
          cache: true
      - name: Download flutter binary artifacts
        run: flutter precache --universal
      - name: Install scoop
        if: runner.os == 'Windows'
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
        shell: pwsh
      - name: Install yq (Windows)
        if: runner.os == 'Windows'
        run: scoop install yq
      - name: Install yq and coreutils (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install yq coreutils
          echo "$(brew --prefix)/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH
      - name: Install dart_test_tools
        run: dart pub global activate dart_test_tools ^6.1.3-pre.2
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Restore dart packages
        run: flutter pub get
        working-directory: ${{ inputs.workingDirectory }}
      - name: Update SDK versions
        run: |
          set -euo pipefail

          dart_version=$(dart --version | cut -d: -f2 | cut '-d(' -f1 | xargs)
          flutter_version=$(flutter --version | grep Flutter | cut -d ' ' -f2 | xargs)

          for pubspec in $(find . -name pubspec.yaml); do
            echo "Updating SDK versions in $pubspec"
            sed -i "s/sdk: \([^\"]*\)/sdk: ^$dart_version/" "$pubspec"
            if grep -q 'flutter:' "$pubspec"; then
              sed -i "s/flutter: .*/flutter: '>=$flutter_version'/" "$pubspec"
            fi
          done
        working-directory: ${{ inputs.workingDirectory }}
      - id: check-for-flutter-test
        name: Install flutter_test if needed
        run: |
          set -euo pipefail

          if flutter pub deps --json | jq '.packages | any(.name == "flutter_test")' | grep -q true; then
            echo "wasInstalled=false" >> $GITHUB_OUTPUT
          else
            flutter pub add 'dev:flutter_test:{sdk: flutter}'
            echo "wasInstalled=true" >> $GITHUB_OUTPUT
          fi
        working-directory: ${{ inputs.workingDirectory }}
      - name: Upgrade all dependencies
        run: |
          set -euo pipefail

          echo '```' > ${{ runner.temp }}/update_log.md
          flutter pub upgrade --major-versions --tighten | tee -a ${{ runner.temp }}/update_log.md
          echo '```' >> ${{ runner.temp }}/update_log.md
        working-directory: ${{ inputs.workingDirectory }}
      - name: Remove flutter_test
        if: steps.check-for-flutter-test.outputs.wasInstalled == 'true'
        run: flutter pub remove flutter_test
        working-directory: ${{ inputs.workingDirectory }}
      - name: Regenerate lockfiles
        if: steps.check-for-flutter-test.outputs.wasInstalled == 'true'
        run: flutter pub upgrade
        working-directory: ${{ inputs.workingDirectory }}
      - name: Update changelog and bump build number
        run: |
          set -euo pipefail

          dart pub global run dart_test_tools:cider log changed 'Updated dependencies'
          dart pub global run dart_test_tools:cider bump patch
          dart pub global run dart_test_tools:cider version-sync
          dart pub global run dart_test_tools:cider release
      - id: create-pull-request
        name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: automatic-dependency-updates
          delete-branch: true
          commit-message: Automatic dependency updates
          title: Automatic dependency updates
          body-path: ${{ runner.temp }}/update_log.md
          assignees: ${{ github.repository_owner }}
          token: ${{ secrets.githubToken }}
      - name: Mention assignees
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
          message: Your review has been requested @${{ github.repository_owner }}
