on:
  workflow_call:
    inputs:
      flutterSdkChannel:
        type: string
        required: false
        default: stable
        description: The Flutter-SDK channel. Passed as "channel" to "subosito/flutter-action".
      javaJdkVersion:
        type: number
        required: false
        default: 17
        description: The Java-SDK version (mayor only). Passed as "java-version" to "actions/setup-java".
      workingDirectory:
        type: string
        required: false
        default: .
        description: The root directory of the dart package to build and test.
      removePubspecOverrides:
        type: boolean
        required: false
        default: true
        description: Disables pubspec_overrides.yaml cleanup if set to false.
      artifactDependencies:
        type: string
        required: false
        default: ""
        description: A space-separated list of package names that should be downloaded from the artifacts and overwritten for the workflow. The packages should be space separated and placed in a single line. You can use the YAML ">-" for that.
      buildRunner:
        type: boolean
        required: false
        default: false
        description: Specify whether build_runner is used in the project (defaults to false).
      buildRunnerArgs:
        type: string
        required: false
        description: Optional additional arguments to be passed to the build runner.
      buildNumberArgs:
        type: string
        required: false
        default: ""
        description: Additional args for the build number generator.
      primaryLocale:
        type: string
        required: false
        default: en-US
        description: The default locale of the app. This is used to set the language of the generated changelogs
    secrets:
      dartDefines:
        required: false
        description: |
          Additional dart-defines that are passed to the build command. In the format of:

          VARIABLE1=value1
          VARIABLE2=value2
      keystore:
        required: true
        description: A base64 encoded java keystore used for signing the android app. Use "cat keystore.jks | openssl base64" to encode it.
      keystorePassword:
        required: true
        description: The primary password for the signing keystore. Must be the password for both, keystore and signing key.
jobs:
  build_android:
    name: Build android app bundle
    runs-on: ubuntu-latest
    steps:
      - name: Install JDK Version ${{ inputs.javaJdkVersion }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.javaJdkVersion }}
      - name: Install Flutter-SDK (${{ inputs.flutterSdkChannel }})
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.flutterSdkChannel }}
          cache: true
      - name: Download flutter binary artifacts
        run: flutter precache --universal --android
      - name: Install dart_test_tools
        run: dart pub global activate dart_test_tools ^5.11.7
      - name: Install scoop
        if: runner.os == 'Windows'
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
        shell: pwsh
      - name: Install yq (Windows)
        if: runner.os == 'Windows'
        run: scoop install yq
      - name: Install yq and coreutils (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install yq coreutils
          echo "$(brew --prefix)/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Remove pubspec_overrides.yaml
        if: inputs.removePubspecOverrides
        run: find . -type f -name "pubspec_overrides.yaml" -exec git rm -f {} \;
        working-directory: ${{ inputs.workingDirectory }}
        shell: bash
      - name: Download artifacts
        if: inputs.artifactDependencies != ''
        uses: actions/download-artifact@v4
        with:
          pattern: package-*
          path: ${{ runner.temp }}/.artifacts
      - name: Create pubspec_overrides.yaml for artifact packages
        if: inputs.artifactDependencies != ''
        run: |
          set -eo pipefail
          if [[ ! -f pubspec_overrides.yaml ]]; then
            yq '{"dependency_overrides": .dependency_overrides}' pubspec.yaml > pubspec_overrides.yaml
          fi
          for package in ${{ inputs.artifactDependencies }}; do
            yq -i ".dependency_overrides.$package.path=\"${{ runner.temp }}/.artifacts/package-$package\"" pubspec_overrides.yaml
          done
        working-directory: ${{ inputs.workingDirectory }}
        shell: bash
      - name: Restore dart packages
        run: flutter pub get
        working-directory: ${{ inputs.workingDirectory }}
      - id: checkGenerate
        name: Check if localizations generation is required
        run: echo "generate=$(yq -r '.flutter.generate // false' pubspec.yaml)" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.workingDirectory }}
        shell: bash
      - name: Generate localization files
        if: steps.checkGenerate.outputs.generate == 'true'
        run: flutter gen-l10n
        working-directory: ${{ inputs.workingDirectory }}
      - name: Create build files
        if: inputs.buildRunner
        run: flutter pub run build_runner build --release ${{ inputs.buildRunnerArgs }}
        working-directory: ${{ inputs.workingDirectory }}
      - id: generateBuildNumber
        name: Generate build number
        run: dart pub global run dart_test_tools:generate_build_number ${{ inputs.buildNumberArgs }}
        working-directory: ${{ inputs.workingDirectory }}
      - name: Prepare dart defines
        run: echo '${{ secrets.dartDefines }}' > '${{ runner.temp }}/dart-defines.env'
        shell: bash
      - name: Prepare signing keystore
        run: |
          set -eo pipefail
          keystore_path='${{ runner.temp }}/app.keystore'
          echo '${{ secrets.keystore }}' | openssl base64 -d > "$keystore_path"
          cat << EOF > android/key.properties
          storeFile=$keystore_path
          password=${{ secrets.keystorePassword }}
          EOF
        working-directory: ${{ inputs.workingDirectory }}
        shell: bash
      - name: Build appbundle
        run: flutter build appbundle --release --build-number=${{ steps.generateBuildNumber.outputs.buildNumber }} --dart-define-from-file='${{ runner.temp }}/dart-defines.env'
        working-directory: ${{ inputs.workingDirectory }}
      - name: Cleanup secure files
        if: always()
        continue-on-error: true
        run: |
          rm -rfv '${{ runner.temp }}/dart-defines.env'
          rm -rfv '${{ inputs.workingDirectory }}/android/key.properties'
          rm -rfv '${{ runner.temp }}/app.keystore'
        shell: bash
      - name: Generate Changelog
        run: |
          set -eo pipefail
          version=$(yq e '.version' pubspec.yaml)
          changelogs_dir='build/app/outputs/metadata/${{ inputs.primaryLocale }}/changelogs'
          mkdir -p "$changelogs_dir"
          dart run cider describe "$version" > "$changelogs_dir/${{ steps.generateBuildNumber.outputs.buildNumber }}.txt"
        working-directory: ${{ inputs.workingDirectory }}
        shell: bash
      - name: Upload app and debug info
        uses: actions/upload-artifact@v4
        with:
          name: app-deployment-appbundle
          path: ${{ inputs.workingDirectory }}/build/app/outputs
          retention-days: 1
          if-no-files-found: error
