name: Continuos Integration and Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      buildRunner: true
      publishExclude: >-
        [
          "lib/src/.gitignore",
          "lib/src/analysis_options.yaml",
          "tool/.gitignore"
        ]
      unitTestPaths: ""
      integrationTestPaths: test/integration
      platforms: '["linux","windows","macos"]'
    secrets:
      integrationTestEnvVars: |
        TEST_KEY=test-value

  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    with:
      buildRunner: true
      publishExclude: >-
        [
          "lib/src/.gitignore",
          "lib/src/analysis_options.yaml",
          "tool/.gitignore"
        ]
    secrets:
      PUB_DEV_CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
