name: CD - Publish to pub.dev

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    with:
      buildRunner: true
