name: Continuos Integration and Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      platforms: '["linux","windows","macos"]'
      buildRunner: true
      unitTestPaths: ""
      integrationTestPaths: test/integration
      integrationTestSetup: >-
        {
          "linux": "dart run tool/ci_install_flutter.dart",
          "windows": "dart run tool/ci_install_flutter.dart",
          "macos": "dart run tool/ci_install_flutter.dart"
        }
    secrets:
      integrationTestEnvVars: |
        TEST_KEY=test-value

  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
