name: CD - Publish to pub.dev

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Tag to create a version from
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    with:
      ref: refs/tags/v${{ inputs.tag }}
      buildRunner: true
