on:
  workflow_call:
    inputs:
      tagPrefix:
        type: string
        required: false
        default: v
        description: The prefix of git tags. The tag is the prefix, followed by the package version.
      version:
        type: string
        required: true
        description: The released version to upload additional files to.
jobs:
  deb_deploy:
    name: Build deb package
    runs-on: ubuntu-latest
    steps:
      - name: Add dart repository
        run: |
          set -eo pipefail
          wget -qO- 'https://dl-ssl.google.com/linux/linux_signing_key.pub' | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
          echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
      - name: Add makedeb repository
        run: |
          set -eo pipefail
          wget -qO- 'https://proget.makedeb.org/debian-feeds/makedeb.pub' | sudo gpg --dearmor -o /usr/share/keyrings/makedeb-archive-keyring.gpg
          echo 'deb [signed-by=/usr/share/keyrings/makedeb-archive-keyring.gpg arch=all] https://proget.makedeb.org/ makedeb main' | sudo tee /etc/apt/sources.list.d/makedeb.list
      - name: Refresh packages cache
        run: sudo apt-get update
      - name: Install needed packages
        run: sudo apt-get install -y dart makedeb
      - name: Install dart_test_tools
        run: dart pub global activate dart_test_tools ^5.1.0
      - name: Disable stripping
        run: |
          set -eo pipefail
          strip_path=$(which strip)
          sudo rm -f "$strip_path"
          cat << 'EOF' | sudo tee "$strip_path" > /dev/null
          #!/bin/bash
          echo "DISABLED: strip $@"
          EOF
          sudo chmod a+x "$strip_path"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: src
      - name: Create deb dir
        run: mkdir deb
      - name: Generate PKGBUILD from dart package
        run: dart pub global run dart_test_tools:generate_pkgbuild --input src --output deb --makedeb
      - name: Update source checksums
        run: makedeb --gen-integ >> PKGBUILD
        working-directory: deb
      - name: Lint PKGBUILD
        run: makedeb --lint
        working-directory: deb
      - name: Build debian package
        run: makedeb -s --no-confirm
        working-directory: deb
      - name: Upload debian package to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tagPrefix }}${{ inputs.version }}
          files: deb/*.deb
