on:
  workflow_call:
    inputs:
      ubuntuVersions:
        type: string
        required: false
        default: '["noble","jammy"]'
        description: A JSON list list of ubuntu version code names to publish for.
      workingDirectory:
        type: string
        required: false
        default: .
        description: The root directory of the dart package to build and test.
      packagecloudRepository:
        type: string
        required: true
        description: The packagecloud repository to publish to.
    secrets:
      packagecloudToken:
        required: true
        description: The access token for the packagecloud upload.
jobs:
  build_deb:
    name: Build deb package
    runs-on: ubuntu-latest
    steps:
      - name: Add dart repository
        run: |
          set -eo pipefail
          wget -qO- 'https://dl-ssl.google.com/linux/linux_signing_key.pub' | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
          echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
      - name: Add makedeb repository
        run: |
          set -eo pipefail
          wget -qO- 'https://proget.makedeb.org/debian-feeds/makedeb.pub' | sudo gpg --dearmor -o /usr/share/keyrings/makedeb-archive-keyring.gpg
          echo 'deb [signed-by=/usr/share/keyrings/makedeb-archive-keyring.gpg arch=all] https://proget.makedeb.org/ makedeb main' | sudo tee /etc/apt/sources.list.d/makedeb.list
      - name: Refresh packages cache
        run: sudo apt-get update
      - name: Install needed packages
        run: sudo apt-get install -y dart makedeb
      - name: Install tools
        uses: Skycoder42/dart_test_tools/.github/actions/install-tools@main
        with:
          withDartTestTools: "true"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: src
      - name: Create deb dir
        run: mkdir deb
      - name: Generate PKGBUILD from dart package
        run: dart pub global run dart_test_tools:generate_pkgbuild --input src/${{ inputs.workingDirectory }} --output deb --makedeb
      - name: Update source checksums
        run: makedeb --gen-integ >> PKGBUILD
        working-directory: deb
      - name: Lint PKGBUILD
        run: makedeb --lint
        working-directory: deb
      - name: Build debian package
        run: makedeb -s --no-confirm
        working-directory: deb
      - name: Upload debian package to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: deb/*.deb
          retention-days: 3
          if-no-files-found: error
  upload_deb:
    name: Upload deb package to packagecloud
    needs:
      - build_deb
    environment: packagecloud
    strategy:
      fail-fast: false
      matrix:
        code-name: ${{ fromJson(inputs.ubuntuVersions) }}
    runs-on: ubuntu-latest
    steps:
      - name: Download debian package
        uses: actions/download-artifact@v4
        with:
          name: debian-package
          path: deb
      - name: Upload debian package to packagecloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.packagecloudToken }}
        uses: lpenz/ghaction-packagecloud@v0.5
        with:
          repository: ${{ inputs.packagecloudRepository }}/${{ matrix.code-name }}
