on:
  workflow_call:
    inputs:
      createAurUpdate:
        type: boolean
        required: true
        description: A boolean indicating whether the AUR-Deploy step should run.
jobs:
  deb_deploy:
    name: Build deb package
    if: inputs.createAurUpdate
    runs-on: ubuntu-latest
    steps:
      - name: Add dart repository
        run: |
          set -eo pipefail
          wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
          echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
          sudo apt-get update
      - name: Install dart
        run: sudo apt-get install -y dart
      - name: Install makedeb
        env:
          MAKEDEB_RELEASE: makedeb
        run: bash -c "$(wget -qO - 'https://shlink.makedeb.org/install')"
      - name: Disable stripping
        run: |
          set -eo pipefail
          strip_path=$(which strip)
          sudo rm -f "$strip_path"
          cat << EOF | sudo tee "$strip_path" > /dev/null
          #!/bin/bash
          echo "DISABLED: strip $@"
          EOF
          sudo chmod a+x "$strip_path"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: src
