on:
  workflow_call:
    inputs:
      dartSdkVersion:
        type: string
        required: false
        default: stable
        description: The Dart-SDK version. Passed as "sdk" to "dart-lang/setup-dart".
      version:
        type: string
        required: true
        description: The previously released version to deploy.
      targetRepo:
        type: string
        required: true
        description: The repository identifier (<owner>/<repo>) to which the cask should be published.
      workingDirectory:
        type: string
        required: false
        default: .
        description: The root directory of the dart package to build and test.
    secrets:
      targetRepoToken:
        required: true
        description: A GitHub PAT that has the permission to push commits to the targetRepo.
jobs:
  deploy_macos:
    name: Deploy DMG image to homebrew tap
    environment: homebrew
    runs-on: macos-latest
    steps:
      - name: Install Dart-SDK (${{ inputs.dartSdkVersion }})
        uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d
        with:
          sdk: ${{ inputs.dartSdkVersion }}
      - name: Install tools
        uses: Skycoder42/dart_test_tools/.github/actions/install-tools@main
        with:
          withDartTestTools: "true"
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
          path: src
      - name: Checkout ${{ inputs.targetRepo }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: true
          path: tap
          repository: ${{ inputs.targetRepo }}
          token: ${{ secrets.targetRepoToken }}
      - id: generate-cask
        name: Generate cask formula
        run: generate-cask --input 'src/${{ inputs.workingDirectory }}' --output tap
      - name: Stage cask update
        run: git add Casks/${{ steps.generate-cask.outputs.caskName }}.rb
        working-directory: tap
      - name: Commit tap update
        run: git -c user.name='github-actions[bot]' -c user.email='41898282+github-actions[bot]@users.noreply.github.com' commit -m 'Updated cask ${{ steps.generate-cask.outputs.caskName }} to v${{ inputs.version }}' --author '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
        working-directory: tap
      - name: Tap local repository
        run: brew tap ${{ inputs.targetRepo }} tap
      - name: Trust local repository
        run: brew trust ${{ inputs.targetRepo }}
      - name: Audit generated cask
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.targetRepoToken }}
        run: brew audit --arch all --strict --git --online --cask '${{ inputs.targetRepo }}/${{ steps.generate-cask.outputs.caskName }}'
      - name: Push tap update to remote
        run: git push origin
        working-directory: tap
