name: Flutter ARM Test

on:
  workflow_dispatch:

env:
  SDK_VERSION: "24.08"

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: org.freedesktop.Sdk.Extension.flutter_${{ env.SDK_VERSION }}_aarch64.flatpak
          manifest-path: flatpak/flutter-extension/org.freedesktop.Sdk.Extension.flutter.arm.yaml
          verbose: true
          cache: false
          upload-artifact: false
          arch: aarch64
