on:
  workflow_call:
    inputs:
      dartSdkVersion:
        type: string
        required: false
        default: stable
        description: The Dart-SDK version. Passed as "sdk" to "dart-lang/setup-dart".
      repository:
        type: string
        required: false
        description: The repository to check out. Passed as "repository" to "actions/checkout".
      workingDirectory:
        type: string
        required: false
        default: .
        description: The root directory of the dart package to build and test.
      releaseRef:
        type: string
        required: false
        default: refs/heads/main
        description: The git ref that is allowed to publish releases.
      tagPrefix:
        type: string
        required: false
        default: v
        description: The prefix of git tags. The tag is the prefix, followed by the package version.
jobs:
  release:
    name: Create release if needed
    if: github.ref == inputs.releaseRef
    runs-on: ubuntu-latest
    steps:
      - name: Install Dart-SDK (${{ inputs.dartSdkVersion }})
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ inputs.dartSdkVersion }}
      - name: Checkout repository ${{ inputs.repository }}
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
      - id: version
        name: Check if package should be published
        run: |
          set -e
          package_name=$(cat pubspec.yaml | yq e ".name" -)
          package_version=$(cat pubspec.yaml | yq e ".version" -)
          version_exists_query=".versions | .[] | select(.version == \"$package_version\") | .version"

          pub_info_file=$(mktemp)
          curl -sSLo $pub_info_file \
            -H "Accept: application/vnd.pub.v2+json" \
            -H "Accept-Encoding: identity" \
            "https://pub.dev/api/packages/$package_name"

          if cat $pub_info_file | jq -e "$version_exists_query" > /dev/null; then
            echo Version already exists on pub.dev - skipping deployment
            echo "update=false" >> $GITHUB_OUTPUT
          else
            echo Version does not exists on pub.dev - creating release
            echo "update=true" >> $GITHUB_OUTPUT
          fi
        working-directory: ${{ inputs.workingDirectory }}
      - name: Activate cider
        if: steps.version.outputs.update == 'true'
        run: dart pub global activate cider
      - id: release_content
        name: Generate release content
        if: steps.version.outputs.update == 'true'
        run: |
          set -e
          package_name=$(cat pubspec.yaml | yq e ".name" -)
          package_version=$(cat pubspec.yaml | yq e ".version" -)

          tag_name="${{ inputs.tagPrefix }}$package_version"
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT

          release_name="Release of package $package_name - Version $package_version"
          echo "release_name=$release_name" >> $GITHUB_OUTPUT

          version_changelog_file=$(mktemp)
          echo "# Changelog" > $version_changelog_file
          dart pub global run cider describe "$package_version" >> $version_changelog_file
          echo "" >> $version_changelog_file
          echo "The package and it's documentation are available at [pub.dev](https://pub.dev/packages/$package_name/versions/$package_version)." >> $version_changelog_file
          echo "body_content<<EOF" >> $GITHUB_OUTPUT
          cat $version_changelog_file >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.workingDirectory }}
      - name: Dispatch release event
        if: steps.version.outputs.update == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: de.skycoder42.dart_test_tools.create-release
          client-payload: '${{ format(''{{"ref": {0}, "tag": {1}, "release": {2}, "body": {3}}}'', toJson(github.ref), toJson(steps.release_content.outputs.tag_name), toJson(steps.release_content.outputs.release_name), toJson(steps.release_content.outputs.body_content)) }}'
