on:
  workflow_call:
    inputs:
      tagPrefix:
        type: string
        required: false
        default: v
        description: The prefix of git tags. The tag is the prefix, followed by the package version.
      dartSdkVersion:
        type: string
        required: false
        default: stable
        description: The Dart-SDK version. Passed as "sdk" to "dart-lang/setup-dart".
      flutter:
        type: boolean
        required: false
        default: false
        description: Specifies, whether the package is a dart or a flutter package.
      flutterSdkChannel:
        type: string
        required: false
        default: stable
        description: The Flutter-SDK channel. Passed as "channel" to "subosito/flutter-action".
      withSubmodules:
        type: boolean
        required: false
        default: false
        description: Specify if submodules should be initialized or not.
      workingDirectory:
        type: string
        required: false
        default: .
        description: The root directory of the dart package to build and test.
      buildDependencies:
        type: string
        required: false
        description: A spaces separated list of other packages within this workspace that make use of build_runner and need to be built before this package.
      buildRunner:
        type: boolean
        required: false
        default: false
        description: Specify whether build_runner is used in the project (defaults to false).
      buildRunnerArgs:
        type: string
        required: false
        description: Optional additional arguments to be passed to the build runner.
      extraArtifacts:
        type: string
        required: false
        description: |
          A JSON-Matrix a artifact download configuration, if needed. Can be used to
          download artifacts before publishing the package. Can be combined with
          `prePublish` to process the downloaded artifacts.

          Example:
          {
            "name": "test-artifact",
            "path": "path/to/artifact-dir"
          }
      prePublish:
        type: string
        required: false
        description: A command to be run before publishing the package
jobs:
  publish:
    name: Publish to pub.dev
    if: startsWith(github.ref, format('refs/tags/{0}', inputs.tagPrefix))
    environment: pub-deploy
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Install Dart-SDK (${{ inputs.dartSdkVersion }})
        if: '!inputs.flutter'
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ inputs.dartSdkVersion }}
      - name: Install Flutter-SDK (${{ inputs.flutterSdkChannel }})
        if: inputs.flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.flutterSdkChannel }}
          cache: true
      - name: Download flutter binary artifacts
        if: inputs.flutter
        run: flutter precache --universal
      - name: Create publishing token (flutter)
        if: inputs.flutter
        run: |
          set -eo pipefail
          PUB_TOKEN=$(curl --retry 5 --retry-connrefused -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=https://pub.dev" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')
          echo "PUB_TOKEN=${PUB_TOKEN}" >> $GITHUB_ENV
          export PUB_TOKEN
          flutter pub token add https://pub.dev --env-var PUB_TOKEN
      - id: tools
        name: Prepare build tools
        run: |
          if ${{ inputs.flutter }}; then
            echo "pub=flutter pub" >> $GITHUB_OUTPUT
            echo "pubRun=flutter pub run" >> $GITHUB_OUTPUT
          else
            echo "pub=dart pub" >> $GITHUB_OUTPUT
            echo "pubRun=dart run" >> $GITHUB_OUTPUT
          fi
      - name: Install tools
        uses: Skycoder42/dart_test_tools/.github/actions/install-tools@main
        with:
          withDartTestTools: "false"
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: ${{ inputs.withSubmodules }}
      - name: Restore dart packages
        run: ${{ steps.tools.outputs.pub }} get
        working-directory: ${{ inputs.workingDirectory }}
      - id: checkGenerate
        name: Check if localizations generation is required
        if: inputs.flutter
        run: |
          set -eo pipefail
          if [ -f l10n.yaml ]; then
            echo "generate=true" >> $GITHUB_OUTPUT
          else
            echo "generate=false" >> $GITHUB_OUTPUT
          fi
        working-directory: ${{ inputs.workingDirectory }}
        shell: bash
      - name: Generate localization files
        if: steps.checkGenerate.outputs.generate == 'true' && inputs.flutter
        run: flutter gen-l10n
        working-directory: ${{ inputs.workingDirectory }}
      - name: Run build_runner for workspace dependencies
        if: inputs.buildDependencies != ''
        run: |
          set -euo pipefail
          for package in ${{ inputs.buildDependencies }}; do
            echo ">> Running build_runner for $package"
            path=$(
              dart pub workspace list --json \
                | jq -r \
                  --arg package "$package" \
                  '.packages[] | select(.name == $package) | .path'
            )
            cd "$path"
            ${{ steps.tools.outputs.pubRun }} build_runner build --delete-conflicting-outputs
          done
        working-directory: ${{ inputs.workingDirectory }}
        shell: bash
      - name: Create build files
        if: inputs.buildRunner
        run: ${{ steps.tools.outputs.pubRun }} build_runner build --release ${{ inputs.buildRunnerArgs }}
        working-directory: ${{ inputs.workingDirectory }}
      - name: Download additional artifacts
        if: inputs.extraArtifacts != ''
        uses: actions/download-artifact@v4
        with:
          name: ${{ fromJSON(inputs.extraArtifacts)['name'] }}
          path: ${{ fromJSON(inputs.extraArtifacts)['path'] }}
      - name: Run pre publish script
        if: inputs.prePublish != ''
        run: ${{ inputs.prePublish }}
        working-directory: ${{ inputs.workingDirectory }}
      - name: Publish package
        run: ${{ steps.tools.outputs.pub }} publish --force
        working-directory: ${{ inputs.workingDirectory }}
